# Generated by Django 4.2.5 on 2023-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
