# Generated by Django 4.2.5 on 2023-09-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_account_accountname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountname',
            new_name='account_name',
        ),
    ]
