# Generated by Django 4.2.5 on 2023-09-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_rename_accountname_account_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=28),
        ),
    ]
