# Generated by Django 4.2.5 on 2023-09-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionType', models.CharField(max_length=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountApp.account')),
            ],
        ),
    ]
